name: n8n
version: "2.1.4"
slug: n8n
description: Self host your n8n instance
url: 'https://github.com/croogie/ha-addons'
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
webui: http://[HOST]:[PORT:5678]/
map:
  - ssl:ro
  - backup:rw
  - share:rw
  - media:rw
  - addon_config:rw
  - homeassistant_config:ro
ports:
  5678/tcp: 5678
ports_description:
  5678/tcp: n8n Web interface
options:
  auth: false
  auth_username: ''
  auth_password: ''
  timezone: Europe/Berlin
  protocol: http
  certfile: fullchain.pem
  keyfile: privkey.pem
  env_vars_list:
    - WEBHOOK_URL: http://localhost:5678
  cmd_line_args: ''
schema:
  auth: "bool"
  auth_username: "str?"
  auth_password: "str?"
  timezone: "str"
  protocol: "str"
  certfile: "str"
  keyfile: "str"
  env_vars_list:
    - "match(^[A-Z_0-9]+: .*$)"
  cmd_line_args: "str?"
